var schema = [
'BEGIN;',
  'CREATE TABLE "matrix_song" (',
      '"id" integer NOT NULL PRIMARY KEY,',
      '"title" varchar(200) NOT NULL,',
      '"artist" varchar(200) NOT NULL,',
      '"album" varchar(200) NOT NULL,',
      '"filename" varchar(256) NOT NULL,',
      '"idx" integer NOT NULL,',
      '"tag" varchar(200) NOT NULL,',
      '"timestamp" datetime NOT NULL,',
      'UNIQUE ("idx", "tag")',
  ')',
  ';',
  'CREATE TABLE "matrix_distance" (',
      '"id" integer NOT NULL PRIMARY KEY,',
      '"songA_id" integer NOT NULL REFERENCES "matrix_song" ("id"),',
      '"songB_id" integer NOT NULL REFERENCES "matrix_song" ("id"),',
      '"distance" real NOT NULL,',
      '"tag" varchar(200) NOT NULL,',
      '"timestamp" datetime NOT NULL,',
      'UNIQUE ("songA_id", "songB_id")',
  ')',
  ';',
  'CREATE INDEX "matrix_distance_songA_id" ON "matrix_distance" ("songA_id");',
  'CREATE INDEX "matrix_distance_songB_id" ON "matrix_distance" ("songB_id");',
'COMMIT;'
].join(" ");

